plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
theme: jekyll-theme-midnight
github:
  is_project_page: false
batfox: https://github.com/Batfoxkid
name: SCP:SF Guide