plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
theme: jekyll-theme-slate
github:
  is_project_page: false
batfox: http://steamcommunity.com/profiles/76561198182419301
bisho: http://steamcommunity.com/profiles/76561198372486554
name: SCP:SF Guide
name_large: "SCP: Secret Fortress"